JavaScript capstone project - Your API-based webapp
Jrmcuervo/js-group-capstone pull request #39
Opened 2023-05-26 22:24 UTC by Jrmcuervo

### JavaScript Capstone
  In this pull request we; 
        

- Build these interfaces: 
       1. The home page. 
       2. The comments popup.  
       3. The reservations popup
       
- Use API documentation.
- Make JavaScript code asynchronous.
- Use callbacks and promises.
- Use AAA pattern for unit tests.
- Follow the layout of the wireframes provided.

- Build counters to show;

     1. The number of items (home).  
     2. The number of comments (comments popup). 
     3. The number of reservations.

2023-05-26 23:08 UTC, Yerimah requested changes
# STATUS: REQUIRED CHANGES 🔴 

Hi @Team, 👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f4d634a5755566852566e493378656f516f6d2f67697068792e676966](https://github.com/Jrmcuervo/js-group-capstone/assets/71140133/2dcb003e-67c4-440d-aa88-4283fd09f667)


## Highlights
- No linter errors 👍 
- All tests are passing 👍 
- Descriptive PR summary and title 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-26 23:08 UTC, Yerimah commented on src/modules/reservePokemon.js
> +    </div>
- [x] Hey guys, you have done a great job so far but there are some issues that need fixing with your project. Firstly, I will suggest that you reduce the height of the reservation and the comment popup to make it easy for comments and reservations to be made.

2023-05-26 23:08 UTC, Yerimah commented on src/modules/likes.js
> +      item_id: index,
- [ ] The like counter feature is not functional. I will advise you to fix this so that when a user clicks on the like icon on their favorite Pokemon card the interaction gets recorded in the [Involvement API](https://www.notion.so/Involvement-API-869e60b5ad104603aa6db59e08150270), and the screen gets updated.

2023-05-27 06:38 UTC, CesarHerr commented on src/modules/likes.js
> +      item_id: index,
@Yerimah  Ok thank you for your review, we'll fix that

2023-05-27 06:42 UTC, CesarHerr commented
-Fixed The like counter feature ✔️ 
- The height of the reservation and the comment popup was reduced.

[pokemon.webm](https://github.com/Jrmcuervo/js-group-capstone/assets/111262493/38799638-72a0-47a4-81d3-0d4bc4159fb1)

2023-05-27 07:11 UTC, osamaashraf6 approved these changes
Hi @Jrmcuervo 😊, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![MinionsGIF (2)](https://github.com/Yordinia/JavaScript-Capstone/assets/83360636/cdfb3a2c-57be-400a-9e41-53c3bc73bbdf)

## Highlights🎉🎉

- [x] Nice design 💯
- [x] Beautiful UI🚀 
- [x] The PR has a proper title and a descriptive body 👍
- [x]  Good using the API for posting data and getting it 👌
## Optional suggestions
- N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-27 07:15 UTC, merged